---
- name: Apt | Dist upgrade to latest
  apt: update_cache=yes upgrade=dist

- name: Nginx | Add apt-key
  apt_key:
   url=http://nginx.org/keys/nginx_signing.key
   state=present
- name:  Nginx | repo to source.list
  lineinfile: 
   dest=/etc/apt/sources.list 
   line="deb http://nginx.org/packages/mainline/{{ distrfamily }} {{ releasename }} nginx"
- name: Nginx | apt update and Nginx install
  apt:
   name=nginx 
   update_cache=yes
- name: Nginx | start
  service:
   name=nginx
   state=started
- include: gitclone.yml
- include: nginx_conf.yml
- include: npm.yml
#Created by Punko <Punkoivan@yandex.ru> on 16.02.16
