---
- name: Git | git install
  apt:
   name=git
   state=present
- name: Git | rm dir with default site, mkdir for repo
  file: name={{ site_root_dir }} state={{ item.state }}
  with_items:
   - { state: absent }
   - { state: directory }
- name: Git | clone
  git:
   repo={{ git_repo }}
   dest={{ site_root_dir }}
   force=yes
#Created by Punko <Punkoivan@yandex.ru> 16.02.16
